version: '3.9'
services:
  mysql:
    hostname: mysql
    image: 'mysql:latest'
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: simple-microservice
  simple-microservice:
    image: simple-microservice
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/simple-microservice
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      SHELTER_CAT_FACT_PROVIDER_URL: http://catninja:8080/fact
    depends_on:
      mysql:
        condition: service_started
  catninja:
    image: catninja
    ports:
      - 8087:8080
    environment:
      SERVER_PORT: 8080